FROM golang:1.19.12 AS BUILDTIME

#RUN git clone --single-branch --branch master https://github.com/19May-IITJ/mta-hosting-optimizer.git /tmp/code \
ADD . /tmp/code

RUN cd /tmp/code \
    && make bin

FROM ubuntu:22.04 AS RUNTIME

COPY --from=BUILDTIME /tmp/code/dist/mta /usr/local/bin/
COPY --from=BUILDTIME /tmp/code/mock/data/ip2.json /etc/configservice/ip2.json

ENV CONFIGSERVICE_PORT="8020"
ENV DBPATH="/etc/configservice/ip2.json"
ENV NATS_URI="nats://nats:4222"

EXPOSE 8020/tcp

ENTRYPOINT ["/usr/local/bin/mta","configservice"]