FROM golang:1.19.12 AS BUILDTIME

#RUN git clone --single-branch --branch master https://github.com/19May-IITJ/mta-hosting-optimizer.git /tmp/code \
ADD . /tmp/code

RUN cd /tmp/code \
    && make bin

FROM ubuntu:22.04 AS RUNTIME

COPY --from=BUILDTIME /tmp/code/dist/mta /usr/local/bin/

ENV MTA_THRESHOLD="10"
ENV HOSTINGSERVICE_PORT="8010"
ENV NATS_URI="nats://nats:4222"

EXPOSE 8010/tcp

ENTRYPOINT ["/usr/local/bin/mta","hostingservice"]