FROM golang:1.19.12 AS BUILDTIME

ADD . /tmp/code

WORKDIR /tmp/code

RUN go test -count=1 -cover ./... \
    && make bin

FROM ubuntu:22.04 AS RUNTIME

COPY --from=BUILDTIME /tmp/code/dist/mta /usr/local/bin/

ENTRYPOINT ["/usr/local/bin/mta","hostingservice"]